apiVersion: v1
kind: PersistentVolume
metadata:
  name: projetweb-pv
  namespace: projetweb
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  storageClassName: slow
