apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projetweb-pvc
  namespace: projetweb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
